name: Heroku Deploy

on:
  push:
    branches:
      - main  # main branch'ine push yapıldığında çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh  # Heroku CLI yükler
          echo $HEROKU_API_KEY | heroku auth:token  # Heroku API key ile giriş yapar
          git remote add heroku https://git.heroku.com/turgo-backend.git  # Heroku git repo bağlantısı
          git push heroku main  # Heroku'ya deploy işlemi yapar

